"""Noncoherent on-off keying modulator hierarchical block."""

# Copyright 2022-2026 James Morrison
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from gnuradio import analog, blocks, gr


def _samples_per_symbol(sample_rate: float, symbol_rate: float) -> int:
    sample_rate = float(sample_rate)
    symbol_rate = float(symbol_rate)
    if sample_rate <= 0 or symbol_rate <= 0:
        raise ValueError("sample_rate and symbol_rate must be positive")
    ratio = sample_rate / symbol_rate
    rounded = round(ratio)
    if rounded < 1 or abs(ratio - rounded) > 1e-9:
        raise ValueError("sample_rate must be an integer multiple of symbol_rate")
    return int(rounded)


class OOKModulator(gr.hier_block2):
    """Convert packed bytes into a complex OOK waveform.

    ``carrier_frequency`` is a digital offset relative to the SDR center
    frequency and must lie within the sampled Nyquist interval.  Use zero for
    complex-envelope OOK.
    """

    def __init__(
        self,
        carrier_frequency: float = 0.0,
        sample_rate: float = 128e3,
        symbol_rate: float = 500.0,
    ):
        self._validate_carrier(carrier_frequency, sample_rate)
        self.carrier_frequency = float(carrier_frequency)
        self.sample_rate = float(sample_rate)
        self.symbol_rate = float(symbol_rate)
        interpolation = _samples_per_symbol(self.sample_rate, self.symbol_rate)

        gr.hier_block2.__init__(
            self,
            "OOK Modulator",
            gr.io_signature(1, 1, gr.sizeof_char),
            gr.io_signature(1, 1, gr.sizeof_gr_complex),
        )

        self._unpack = blocks.unpack_k_bits_bb(8)
        self._to_float = blocks.uchar_to_float()
        self._repeat = blocks.repeat(gr.sizeof_float, interpolation)
        self._to_complex = blocks.float_to_complex(1)
        self._carrier = analog.sig_source_c(
            self.sample_rate,
            analog.GR_COS_WAVE,
            self.carrier_frequency,
            1.0,
            0.0,
        )
        self._multiply = blocks.multiply_vcc(1)

        self.connect(self, self._unpack, self._to_float, self._repeat)
        self.connect(self._repeat, self._to_complex, (self._multiply, 0))
        self.connect(self._carrier, (self._multiply, 1))
        self.connect(self._multiply, self)

    @staticmethod
    def _validate_carrier(carrier_frequency: float, sample_rate: float) -> None:
        if float(sample_rate) <= 0:
            raise ValueError("sample_rate must be positive")
        if abs(float(carrier_frequency)) >= float(sample_rate) / 2:
            raise ValueError(
                "carrier_frequency is a digital offset and must satisfy "
                "abs(carrier_frequency) < sample_rate / 2"
            )

    def get_carrier_frequency(self):
        return self.carrier_frequency

    def set_carrier_frequency(self, carrier_frequency):
        self._validate_carrier(carrier_frequency, self.sample_rate)
        self.carrier_frequency = float(carrier_frequency)
        self._carrier.set_frequency(self.carrier_frequency)

    def get_sample_rate(self):
        return self.sample_rate

    def set_sample_rate(self, sample_rate):
        self._validate_carrier(self.carrier_frequency, sample_rate)
        interpolation = _samples_per_symbol(sample_rate, self.symbol_rate)
        self.sample_rate = float(sample_rate)
        self._carrier.set_sampling_freq(self.sample_rate)
        self._repeat.set_interpolation(interpolation)

    def get_symbol_rate(self):
        return self.symbol_rate

    def set_symbol_rate(self, symbol_rate):
        interpolation = _samples_per_symbol(self.sample_rate, symbol_rate)
        self.symbol_rate = float(symbol_rate)
        self._repeat.set_interpolation(interpolation)

    # Compatibility with flowgraphs generated by the 2022 release.
    get_carrier_freq = get_carrier_frequency
    set_carrier_freq = set_carrier_frequency
    get_samp_rate = get_sample_rate
    set_samp_rate = set_sample_rate
