"""Noncoherent on-off keying demodulator hierarchical block."""

# Copyright 2022-2026 James Morrison
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

from gnuradio import blocks, gr

from .ook_modulator import _samples_per_symbol


class OOKDemodulator(gr.hier_block2):
    """Recover packed bytes from an ideally timed complex OOK waveform.

    The block performs noncoherent envelope detection.  It intentionally does
    not perform symbol timing recovery; the input must be aligned to the first
    sample of each symbol, as produced by :class:`OOKModulator`.
    """

    def __init__(
        self,
        sample_rate: float = 128e3,
        symbol_rate: float = 500.0,
        threshold: float = 0.5,
    ):
        self.sample_rate = float(sample_rate)
        self.symbol_rate = float(symbol_rate)
        self.threshold = float(threshold)
        if self.threshold <= 0:
            raise ValueError("threshold must be positive")
        decimation = _samples_per_symbol(self.sample_rate, self.symbol_rate)

        gr.hier_block2.__init__(
            self,
            "OOK Demodulator",
            gr.io_signature(1, 1, gr.sizeof_gr_complex),
            gr.io_signature(1, 1, gr.sizeof_char),
        )

        self._magnitude_squared = blocks.complex_to_mag_squared(1)
        self._threshold = blocks.threshold_ff(
            self.threshold * self.threshold,
            self.threshold * self.threshold,
            0.0,
        )
        self._sample = blocks.keep_one_in_n(gr.sizeof_float, decimation)
        self._to_char = blocks.float_to_char(1, 1.0)
        self._pack = blocks.unpacked_to_packed_bb(1, gr.GR_MSB_FIRST)

        self.connect(
            self,
            self._magnitude_squared,
            self._threshold,
            self._sample,
            self._to_char,
            self._pack,
            self,
        )

    def get_sample_rate(self):
        return self.sample_rate

    def set_sample_rate(self, sample_rate):
        decimation = _samples_per_symbol(sample_rate, self.symbol_rate)
        self.sample_rate = float(sample_rate)
        self._sample.set_n(decimation)

    def get_symbol_rate(self):
        return self.symbol_rate

    def set_symbol_rate(self, symbol_rate):
        decimation = _samples_per_symbol(self.sample_rate, symbol_rate)
        self.symbol_rate = float(symbol_rate)
        self._sample.set_n(decimation)

    def get_threshold(self):
        return self.threshold

    def set_threshold(self, threshold):
        threshold = float(threshold)
        if threshold <= 0:
            raise ValueError("threshold must be positive")
        self.threshold = threshold
        squared = threshold * threshold
        self._threshold.set_hi(squared)
        self._threshold.set_lo(squared)

    # Compatibility with flowgraphs generated by the 2022 release.
    get_samp_rate = get_sample_rate
    set_samp_rate = set_sample_rate
